"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# note: help files should be loaded by the package

APP = ['NUCOS.py']
Plist = {}
OPTIONS = {'argv_emulation': False, # this puts the names of dropped files into sys.argv when starting the app.
           'iconfile': '../Icons/NUCOS.icns',
           'plist': Plist,
           }

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# # Old py2app configuration
# if sys.platform == 'darwin':
#     DATA_FILES = ['nucos/Help']

#     Plist = {}
#     OPTIONS = {'argv_emulation': False, # this puts the names of dropped files into sys.argv when starting the app.
#                'iconfile': 'Icons/NUCOS.icns',
#                'plist': Plist,
#                }

#     setup(
#         name="wxnucos",
#         app=[MainScript, ],
#         packages=['wxnucos'],
#         data_files=DATA_FILES,
#         version=get_version("wxnucos"),
#         description=description,
#         author=author,
#         author_email=author_email,
#         options={'py2app': OPTIONS},
#         # setup_requires=['py2app'],
#     )
